version: '3'

services:
  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "20000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging