version: '3'

services:
  notesms:
    image: notesms
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "20010:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - notesms-network
    depends_on:
      - "notesmspgsql"

  notesmspgsql:
    platform: linux/x86_64
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: notesms
      POSTGRES_PASSWORD: planner
      POSTGRES_DB: notesms
    ports:
      - "5410:5432"
    networks:
      - notesms-network

networks:
  notesms-network:
    driver: bridge