// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Store.PostgreSQL.Database;

#nullable disable

namespace Store.PostgreSQL.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.2.23128.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Templates");
                });

<<<<<<< HEAD:src/TemplatesMS/src/Store.PostgreSQL/Migrations/ContextModelSnapshot.cs
            modelBuilder.Entity("Core.Entities.Widget", b =>
=======
            modelBuilder.Entity("Core.Entities.User.User", b =>
>>>>>>> a3cca7bbadd671b8811f2ff26e7d04999df126b6:src/UserMS/src/Store.PostgreSQL/Migrations/ContextModelSnapshot.cs
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

<<<<<<< HEAD:src/TemplatesMS/src/Store.PostgreSQL/Migrations/ContextModelSnapshot.cs
                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");
=======
                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BirthDate");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Email");
>>>>>>> a3cca7bbadd671b8811f2ff26e7d04999df126b6:src/UserMS/src/Store.PostgreSQL/Migrations/ContextModelSnapshot.cs

                    b.ToTable("Widget");
                });

            modelBuilder.Entity("TemplateWidget", b =>
                {
                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("WidgetsId")
                        .HasColumnType("integer");

<<<<<<< HEAD:src/TemplatesMS/src/Store.PostgreSQL/Migrations/ContextModelSnapshot.cs
                    b.HasKey("TemplateId", "WidgetsId");

                    b.HasIndex("WidgetsId");
=======
                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");
>>>>>>> a3cca7bbadd671b8811f2ff26e7d04999df126b6:src/UserMS/src/Store.PostgreSQL/Migrations/ContextModelSnapshot.cs

                    b.ToTable("TemplateWidgets", (string)null);
                });

<<<<<<< HEAD:src/TemplatesMS/src/Store.PostgreSQL/Migrations/ContextModelSnapshot.cs
            modelBuilder.Entity("TemplateWidget", b =>
                {
                    b.HasOne("Core.Entities.Template", null)
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Widget", null)
                        .WithMany()
                        .HasForeignKey("WidgetsId")
                        .OnDelete(DeleteBehavior.Cascade)
=======
                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Core.Entities.User.User", b =>
                {
                    b.OwnsOne("Core.Entities.User.Password", "Password", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("integer");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PasswordHash");

                            b1.Property<string>("Salt")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PasswordSalt");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Password")
>>>>>>> a3cca7bbadd671b8811f2ff26e7d04999df126b6:src/UserMS/src/Store.PostgreSQL/Migrations/ContextModelSnapshot.cs
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
