// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Store.PostgreSQL.Database;

#nullable disable

namespace Store.PostgreSQL.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230423002510_Migration3")]
    partial class Migration3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.2.23128.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Checklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedOn")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("DeletedOn")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedOn")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Checklist");
                });

<<<<<<< HEAD:src/ChecklistMS/src/Store.PostgreSQL/Migrations/20230423002510_Migration3.Designer.cs
            modelBuilder.Entity("Core.Entities.TaskCheckbox", b =>
=======
            modelBuilder.Entity("Core.Entities.User.User", b =>
>>>>>>> fe76b3b05c9eee7f385bfdd55136067771180f3f:src/UserMS/src/Store.PostgreSQL/Migrations/ContextModelSnapshot.cs
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

<<<<<<< HEAD:src/ChecklistMS/src/Store.PostgreSQL/Migrations/20230423002510_Migration3.Designer.cs
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<DateTimeOffset>("CompletionDate")
=======
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BirthDate");

                    b.Property<DateTime>("CreatedOn")
>>>>>>> fe76b3b05c9eee7f385bfdd55136067771180f3f:src/UserMS/src/Store.PostgreSQL/Migrations/ContextModelSnapshot.cs
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedOn")
                        .IsRequired()
<<<<<<< HEAD:src/ChecklistMS/src/Store.PostgreSQL/Migrations/20230423002510_Migration3.Designer.cs
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");
=======
                        .HasColumnType("text")
                        .HasColumnName("Email");
>>>>>>> fe76b3b05c9eee7f385bfdd55136067771180f3f:src/UserMS/src/Store.PostgreSQL/Migrations/ContextModelSnapshot.cs

                    b.Property<string>("DeletedOn")
                        .HasColumnType("text");

                    b.Property<int>("IdChecklist")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

<<<<<<< HEAD:src/ChecklistMS/src/Store.PostgreSQL/Migrations/20230423002510_Migration3.Designer.cs
                    b.Property<string>("UpdatedOn")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TaskCheckbox");
=======
                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Core.Entities.User.User", b =>
                {
                    b.OwnsOne("Core.Entities.User.Password", "Password", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("integer");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PasswordHash");

                            b1.Property<string>("Salt")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PasswordSalt");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Password")
                        .IsRequired();
>>>>>>> fe76b3b05c9eee7f385bfdd55136067771180f3f:src/UserMS/src/Store.PostgreSQL/Migrations/ContextModelSnapshot.cs
                });
#pragma warning restore 612, 618
        }
    }
}
